name: "Terraform - Staging"
# https://gaunacode.com/deploying-terraform-at-scale-with-github-actions

#name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Change to prod directory
        run: cd prod
      
      - name: Initialize working directory
        run: terraform init
      
      - name: Plan changes
        run: terraform plan
      
      - name: Apply changes
        run: terraform apply
